-- Question 1: Find the orders from clients in the USA
SELECT c.Name, o.OrderID
FROM ORDERS o JOIN CUSTOMERS c ON o.CUSTOMERID = c.CUSTOMERID
WHERE COUNTRY = 'USA';

-- Question 2: Find total Revenue per product
SELECT p.PRODUCTNAME, CAST(SUM(p.PRICE * o.QUANTITY) AS DECIMAL(10,2)) AS TotalRevenue
FROM PRODUCTS p JOIN ORDERS o ON p.PRODUCTID = o.PRODUCTID
GROUP BY p.PRODUCTID;

-- Question 3: Find the customer with the most orders
SELECT c.NAME, COUNT(o.ORDERID) AS TotalOrders
FROM CUSTOMERS c JOIN ORDERS o ON c.CUSTOMERID = o.CUSTOMERID
GROUP BY c.NAME
ORDER BY TotalOrders DESC
LIMIT 1;

-- Question 4: Find Products that they have never been bought
SELECT p.PRODUCTNAME 
FROM PRODUCTS p
WHERE p.PRODUCTID NOT IN (
SELECT o.PRODUCTID
FROM ORDERS o);

-- Question 5: Find average amount of order per customer
SELECT c.NAME, AVG(p.PRICE * o.QUANTITY) AS AVERAGE_ORDER
FROM ORDERS o JOIN CUSTOMERS c  ON c.CUSTOMERID = o.CUSTOMERID
JOIN PRODUCTS P ON p.PRODUCTID = o.PRODUCTID
GROUP BY c.NAME;

-- Question 6: Find how many orders have been completed per country
SELECT c.COUNTRY, COUNT(o.ORDERID) AS NUMBER_OF_ORDERS
FROM ORDERS o JOIN CUSTOMERS c ON c.CUSTOMERID = o.CUSTOMERID
GROUP BY c.COUNTRY;

-- Question 7: FInd the top 2 products with the most orders
SELECT p.PRODUCTNAME, SUM(o.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS p JOIN ORDERS o ON p.PRODUCTID = o.PRODUCTID
GROUP BY p.PRODUCTNAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 2;

-- Question 8: Find customers with NO orders
SELECT c.NAME 
FROM CUSTOMERS c
WHERE c.CUSTOMERID NOT IN(
SELECT o.CUSTOMERID
FROM ORDERS o);

-- Question 9: Find the total orders per month
SELECT MONTH(o.ORDERDATE), COUNT(o.ORDERID) AS TOTAL_ORDERS
FROM ORDERS o
GROUP BY MONTH(o.ORDERDATE);

-- Question 10: Find the average order per country
SELECT c.COUNTRY, AVG(p.PRICE * o.QUANTITY) AS AVERAGE_ORDER
FROM ORDERS o JOIN CUSTOMERS c ON c.CUSTOMERID = o.CUSTOMERID
JOIN PRODUCTS p ON p.PRODUCTID = o.PRODUCTID
GROUP BY c.COUNTRY;

-- Question 11: Find the most expensive order and the client that made it
SELECT c.NAME, (p.PRICE*o.QUANTITY) AS MAX_ORDER
FROM ORDERS o JOIN PRODUCTS p ON p.PRODUCTID = o.PRODUCTID
JOIN CUSTOMERS c ON c.CUSTOMERID = o.CUSTOMERID
ORDER BY MAX_ORDER DESC
LIMIT 1;

-- Question 12: Find products with revenue > 100
SELECT p.PRODUCTNAME , SUM(p.PRICE * o.QUANTITY) AS TOTAL_REVENUE
FROM ORDERS o JOIN PRODUCTS p ON o.PRODUCTID = p.PRODUCTID
GROUP BY p.PRODUCTNAME
HAVING TOTAL_REVENUE > 100;






